fx_version 'cerulean'
game 'gta5'
lua54 'yes'

name 'core-skins-stream'
description 'Pacote unificado de skins de armas - stream por arma, sem duplicatas e sem assets corrompidos'
version '2.0.0'

client_script 'client.lua'

files {
    'data/**/*.meta',
    'data/_level/*.dat',
    'stream/**/*.ytyp',
    'dlccustomweaponsounds/*.awc',
    'sounds_dat/**/*.dat151.rel',
    'sounds_dat/**/*.dat54.rel',
}

before_level_meta 'data/_level/core_skins_fx'

-- ==================== weapon data ====================
data_file 'WEAPONINFO_FILE'           'data/**/*.weapons.meta'
data_file 'WEAPON_METADATA_FILE'      'data/**/*.archetypes.meta'
data_file 'WEAPONCOMPONENTSINFO_FILE' 'data/**/*.components.meta'
data_file 'WEAPON_ANIMATIONS_FILE'    'data/**/*.animations.meta'
data_file 'PED_PERSONALITY_FILE'      'data/**/*.personality.meta'

-- ==================== audio (OMEX) ====================
data_file 'AUDIO_WAVEPACK'  'dlccustomweaponsounds'
data_file 'AUDIO_SOUNDDATA' 'sounds_dat/kawai_sounds.dat'
data_file 'AUDIO_GAMEDATA'  'sounds_dat/kawai_game.dat'
data_file 'AUDIO_GAMEDATA'  'sounds_dat/kawaiex_game.dat'
data_file 'AUDIO_SOUNDDATA' 'sounds_dat/darkmatter_sounds.dat'
data_file 'AUDIO_GAMEDATA'  'sounds_dat/darkmatter_game.dat'

-- ==================== ytyp (181) ====================
data_file 'DLC_ITYP_REQUEST' 'stream/_shared/ytyp/angel_camo01.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/_shared/ytyp/anim_weapons_omex_beta.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/_shared/ytyp/ap_demon_anim.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/_shared/ytyp/aprgb_anim.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/_shared/ytyp/assaultrgb_anim.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/_shared/ytyp/assaultriflemk2_kawai.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/_shared/ytyp/bat_kawai.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/_shared/ytyp/carbineriflemk2_kawai.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/_shared/ytyp/carbineriflemk2_steampunk.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/_shared/ytyp/demon_effect.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/_shared/ytyp/fireflayeffect.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/_shared/ytyp/fireflayeffectg36b.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/_shared/ytyp/fireflayeffectglock.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/_shared/ytyp/g3_heart.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/_shared/ytyp/g3lc_hellfire.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/_shared/ytyp/grgb_anim.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/_shared/ytyp/kdemon_effect.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/_shared/ytyp/krgb_anim.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/_shared/ytyp/nany_copa_camos.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/_shared/ytyp/nomadrgb_anim.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/_shared/ytyp/omex_animetion_v001.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/_shared/ytyp/omex_steampunk_appistol.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/_shared/ytyp/omex_steampunk_pistol.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/_shared/ytyp/omex_weapon_graveyard.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/_shared/ytyp/pdw_kawai.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/_shared/ytyp/pistolrgb_anim.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/_shared/ytyp/pl_penhashop_heavyrifle_ani_natal.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/_shared/ytyp/smg_steampunk_anim.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/_shared/ytyp/specialcarbinemk2_steampunk.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/_shared/ytyp/specialcarbineriflemk2_kawai.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/_shared/ytyp/w_kawai_extended.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/_shared/ytyp/weapon_heavysnipermk2_darkmatter.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/_shared/ytyp/weapons_darkmatter.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/_shared/ytyp/weapons_ice_anim.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/_shared/ytyp/weapons_irondust_magicpunk_anim.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/_shared/ytyp/whitefire_knife19_camo1.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/WEAPON_AK_FROST/weapon_assaultriflemk2_permafrost_anim.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/WEAPON_AKANGELDEMONFLAY/w_ar_akdangeldemonflay_camo1.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/WEAPON_AKFUTUREPLF/plf_assaultrifle_future_camo1.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/WEAPON_AKOFGODFLAY/w_flk_akofgodflay_camo1.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/WEAPON_AKZEUSFLAY/w_ar_akzeusflay_camo1.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/WEAPON_APPISTOL_FUTUREPLF/plf_future_appistol_camo1.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/WEAPON_APPISTOL_GOLD/eo_appistol_didi_camo.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/WEAPON_APPISTOL_GOLDSTORM/nany_goldstorm_pistolmk21_camo1.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/WEAPON_APPISTOL_GREENSTORM/w_pi_pistolmk2_green_camo1.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/WEAPON_APPISTOL1_STORM/w_pi_pistolmk21_camo1.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/WEAPON_ASSAULTRIFLE_GOLDSTORM/nany_goldstorm_assaultrifle01_camo1.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/WEAPON_ASSAULTRIFLE_GREENSTORM/w_ar_assaultrifle_green_camo1.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/WEAPON_ASSAULTRIFLE1_STORM/w_ar_assaultrifle01_camo1.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/WEAPON_ASSAULTSMG_FUTUREPLF/plf_future_smg_camo1.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/WEAPON_AWPFUJINFLAY/w_flk_awpfujinflay_camo1.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/WEAPON_BAT_GREENSTORM/w_me_bat_greenstorm_camo1.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/WEAPON_BAT1/w_me_bat_bat1_camo1.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/WEAPON_BULLPUP_ANIME/w_ar_bullpupriflemk2_anime_camo1.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/WEAPON_BULMA/whitefirenoroes_carbinemk2_bulma_camo1.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/WEAPON_CARBINERIFLE_MK2_SCORPION_GOLD/eo_carbinerifle_mk2_scorpion_gold_camo.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/WEAPON_CARBINERIFLEMK2_BLACKSNAKE/eliel@eo_carbineriflemk2_blacksnake_camo.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/WEAPON_CARBINERIFLEMK2_FUTURE/plf_carbineriflemk2_future_camo1.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/WEAPON_CARBINERIFLEMK2_TIGER/eo_tiger_anim.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/WEAPON_EO_CARBINERIFLEMK2_HALLOWEEN/eo_halloween_carbineriflemk2_camo.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/WEAPON_EO_CARBINERIFLEMK2_POLICE/eo_ar_carbineriflemk2_civil_police_camo.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/WEAPON_EO_CHAMPIONS_APPISTOL/eo_appistol_champions_camo.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/WEAPON_EO_HALLOWEEN_SPECIALCARBINEMK2/eo_specialcarbinemk2_halloween_camo.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/WEAPON_EO_KATANA_GOLD/eo_katana_fire_anim.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/WEAPON_EO_PACKRGX_APPISTOL2/eo_rgx_pistolmk2_anim.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/WEAPON_EO_PACKRGX_ASSAULTRIFLE/eo_rgx_assaultriflemk2_anim.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/WEAPON_EO_PACKRGX_KNIFE/eo_rgx_knife.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/WEAPON_EO_PACKRGX_MACHINEPISTOL/eo_rgx_compactsmg.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/WEAPON_EO_PACKRGX_SPECIALCARBINE2/eo_rgx_specialcarbine_anim.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/WEAPON_EO_REDFIRE_APPISTOL/eo_appistol_redfire_camo.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/WEAPON_EO_REDFIRE_SPECIALCARBINEMK2/eo_specialcarbinemk2_redfire_anim.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/WEAPON_EOCHAMPIONS_SPECIALCARBINEMK2/eo_specialcarbinemk2_champions_camo.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/WEAPON_FAL_CAVEIRA/eo_fal_corrente_anim.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/WEAPON_FAL_VEDITA/eo_fal_raio_anim.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/WEAPON_FALLLOVECATFLAY/w_flk_falllovecatflay_camo1.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/WEAPON_FALLWIREYELLOWFLAY/w_ar_fallwireyellowflay_camo1.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/WEAPON_FALLZEUSFLAY/w_ar_fallzeusflay_camo1.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/WEAPON_FIVE_FROST/pistol_ice_p_ani_01.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/WEAPON_FIVEARARABRFLAY/w_flk_fiveararabrflay_camo1.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/WEAPON_FIVEFUJINFLAY/w_flk_fivefujinflay_camo1.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/WEAPON_FIVERYUJINFLAY/w_flk_fiveryujinflay_camo1.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/WEAPON_FIVESILENTSPIRITFLAY/w_ar_pistolsilentspiritflay_camo1.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/WEAPON_FIVESTREETPURPLEFLAY/w_ar_fivepurplestreetflay_camo1.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/WEAPON_FIVEZEUSFLAY/w_ar_fivezeusflay_camo1.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/WEAPON_FUJINGLOCKRFLAY/w_flk_glockrajadafujinflay_camo1.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/WEAPON_G3_FROST/weapon_specialcarbine_permafrost_anim.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/WEAPON_G36DRAGONPINKWIREFLAY/dragonpinkwiree_camo1.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/WEAPON_G36DRAGONWIREFLAY/dragonwiree_camo1.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/WEAPON_G36DRAGONYELLOWWIREFLAY/dragonyellowwiree_camo1.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/WEAPON_G36FUJINFLAY/w_flk_g36fujinflay_camo1.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/WEAPON_G36LOVELDTFLAY/w_flk_g36bloveldtflay_camo1.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/WEAPON_G36PIKACHUFLAY/pikachu_camo1.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/WEAPON_G36PINKFLOWERFLAY/w_ar_g36pinkflowerflay_camo1.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/WEAPON_G36RYUJINFLAY/w_flk_g36ryujinflay_camo1.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/WEAPON_G36SDEMONANGELFLAY/w_ar_g36sdemonangelflay_camo1.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/WEAPON_G36STREETPURPLEFLAY/w_ar_g36purplestreetflay_camo1.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/WEAPON_G3BLOVECATFLAY/w_ar_g36blovecatflay_camo1.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/WEAPON_G3BWIREYELLOWFLAY_MK2/g36battlewireyellowflay_camo1.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/WEAPON_G3DRAGONRUSTICFLAY/w_ar_g36dragonrusticflay_camo1.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/WEAPON_G3FMEDUSEFLAY/w_flk_g36fmeduseflay_camo1.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/WEAPON_G3HELLFIRE/g3_hellfire.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/WEAPON_G3MK2_FUTUREPLF/plf_logo_3d_anim.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/WEAPON_G3SILENTSPIRITFLAY/w_ar_g36silentspiritflay_camo1.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/WEAPON_G3SIXSEVENFLAY/w_ar_g36sixsevenflay_camo1.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/WEAPON_G3ZEUSFLAY/w_ar_g36zeusflay_camo1.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/WEAPON_GLOCKARARABRFLAY/w_flk_glockararabrflay_camo1.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/WEAPON_GLOCKRAJADADEMONANGELFLAY/w_ar_glockrajadademonangelflay_camo1.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/WEAPON_GLOCKRAJADAWIREYELLOWFLAY/w_ar_glockrajadawireyellowflay_camo1.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/WEAPON_GLOCKRARARABRFLAY/w_flk_glockrajadaararabrflay_camo1.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/WEAPON_GLOCKRLOVECATFLAY/w_flk_glockrlovecatflay_camo1.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/WEAPON_GLOCKRLOVELDTFLAY/w_flk_glockrloveldtflay_camo1.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/WEAPON_GLOCKSIXSEVENFLAY/w_ar_glocksixsevenflay_camo1.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/WEAPON_KDEMONANGELFLAY/w_karambitdemonangelflay_att.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/WEAPON_KFUJINFLAY/w_flk_knifefujinflay_camo1.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/WEAPON_KNIFE_GOLDSTORM/nany_goldstorm_knife_02_camo1.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/WEAPON_KNIFE_GREENSTORM/w_me_knife_greenstorm_camo1.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/WEAPON_KNIFECOPA/eo_knife_worldcup_camo.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/WEAPON_KNIFEFUTUREPLF/w_me_knifefutureplf_camo1.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/WEAPON_KNIFEHELLFIRE/nany_hellfire_knife_camo1.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/WEAPON_KNIFELOVELDTFLAY/w_flk_knifeloveldtflay_camo1.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/WEAPON_KRYUJINFLAY/w_flk_kniferyujinflay_camo1.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/WEAPON_KSILENTSPIRITFLAY/w_ar_facalsilentspiritflay_camo1.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/WEAPON_KSTREETZEUSFLAY/w_ar_knifepurplestreetflay_camo1.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/WEAPON_KWIREYELLOWFLAY/karambit_yellowwireflaycamo1.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/WEAPON_KZEUSFLAY/karambit_zeusflay_camo1.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/WEAPON_LDTDG36BFLAY/w_flk_ldtdg36bflay_camo1.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/WEAPON_M16ZEUSFLAY/w_ar_m16zeusflay_camo1.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/WEAPON_M4A1ZEUSFLAY/w_ar_m4a1zeusflay_camo1.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/WEAPON_M4A4GODFLAY/w_flk_m4a4ofgodflay_camo1.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/WEAPON_M4A4ZEUSFLAY/w_ar_m4a4zeusflay_camo1.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/WEAPON_M4ANIME/eo_m4anime_anim.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/WEAPON_MACHINEPISTOL_GOLDSTORM/nany_goldstorm_microsmg01_camo1.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/WEAPON_MICROSMG_GREENSTORM/w_sb_microsmg_green_camo1.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/WEAPON_MICROSMG1/w_sb_microsmg01_camo1.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/WEAPON_MP5ANGELDEMONFLAY/w_ar_mp5angeldemonflay_camo1.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/WEAPON_MP5ZEUSFLAY/w_ar_mp5zeusflay_camo1.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/WEAPON_MTARSILENTSPIRITFLAY/w_ar_mtarsilentspiritflay_camo1.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/WEAPON_MTARZEUSFLAY/w_ar_mtarzeusflay_camo1.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/WEAPON_ONI/whitefire_carbinemk2_camo1.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/WEAPON_PENHASHOP_BULLPUPRIFLEMK2_NATAL/w_ar_bullpupriflemk2_natal_camo1.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/WEAPON_PENHASHOP_PISTOLMK2_NATAL/nany_pistolmk2_natal_camo1.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/WEAPON_PI_APPIKACHUFLAY/appistolpikachuflay_camo1.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/WEAPON_PI_APZEUSFLAY/w_pi_appistolzeusflay_camo1.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/WEAPON_PI_GLOCKDOCEFLAY/w_pi_rajadadoceflay_camo1.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/WEAPON_PI_GLOCKRSTREETPURPLEFLAY/w_ar_glockrajadapurplestreetflay_camo1.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/WEAPON_PINKFIRE/nany_pinkfire_carbinemk2_camo1.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/WEAPON_PINKFIRE_APPISTOL/pinkfire_appistol_camo1.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/WEAPON_PISTOLMK2_COPA/nany_pistolmk2_copa_camo1.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/WEAPON_PL_FACA_LEVELUP_G/pl_ani_knife_levelup.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/WEAPON_PL_G3_LEVELUP_G/pl_ani_g3_lu_g.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/WEAPON_PL_MTAR_LEVELUP_G/pl_ani_mtar.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/WEAPON_PL_PENHASHOP_G3_GALAXY/pl_penhashop_g3_galaxy_ani_y.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/WEAPON_PL_PENHASHOP_G3_HALLOWEEN/pl_penhashop_g3_halloween_ani.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/WEAPON_PL_PENHASHOP_MTAR_GALAXY/pl_penhashop_mtar_galaxy_ani.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/WEAPON_PL_PENHASHOP_PISTOL_GALAXY/pl_penhashop_pistol_galaxy_ani.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/WEAPON_PL_PENHASHOP_PISTOL_HALLOWEEN_AUTO/pl_penhashop_pistol_halloween_anim1.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/WEAPON_PL_PISTOL_LEVELUP_G/pl_ani_pistol_levelup.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/WEAPON_RAIJIN/whitefire_appistol_camo1.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/WEAPON_RAJADALDTMEDALFLAY/w_flk_rajadaldtmedalflay_camo1.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/WEAPON_SCORPION_M4/eliel@eo_scorpion.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/WEAPON_SHINIGAMI/whitefire_sniper_camo1.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/WEAPON_SMG_MICROARARABRFLAY/w_flk_uziararabrflay_camo1.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/WEAPON_SPECIALCARBINE_BLUESTORM/nany_bluestorm_carbinemk2_camo1.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/WEAPON_SPECIALCARBINE_G3_GOLD/eo_specialcarbinemk2_g3_gold_anim.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/WEAPON_SPECIALCARBINE_GOLDFIRE/eliel@eo_specialcarbinemk2_goldfire_anim.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/WEAPON_SPECIALCARBINE_GOLDSTORM/nany_goldstorm_specialcarbine1_camo1.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/WEAPON_SPECIALCARBINE_GREENSTORM/w_ar_specialcarbine_green_camo1.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/WEAPON_SPECIALCARBINE_NATAL/nany_specialcarbine_natal_camo1.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/WEAPON_SPECIALCARBINE_TOXIC/eo_w_at_ar_afgrip_g3_toxic.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/WEAPON_SPECIALCARBINE_TOXIC/w_ar_specialcarbine_toxic_camo_01.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/WEAPON_SPECIALCARBINE1_STORM/w_ar_specialcarbine1_camo1.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/WEAPON_SPECIALCARBINEMK2_AURA_BLACK_ONI/eo_specialcarbinemk2_aura_black_oni_camo.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/WEAPON_SPECIALCARBINEMK2_AURA_WHITE/eo_specialcarbinemk2_aura_white_camo.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/WEAPON_SPECIALCARBINEMK2COPA/eo_specialcarbinemk2_worldcup.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/WEAPON_SPRSTREETPURPLEFLAY/w_ar_awppurplestreetflay_camo1.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/WEAPON_TACODOCEFLAY/w_me_tacodoceflay.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/WEAPON_TACOZEUSFLAY/w_ar_tacozeusflay_fire.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/WEAPON_TECNINEFUTUREPLF/plf_compactsmg_future_camo1.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/WEAPON_VEDITA/whitefirenoroes_carbinemk2_camo1.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/WEAPON_WOLFSTORM/eo_wolfstorm_anim.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/WEAPON_WOLFSTORM_PURPLE/eliel@eo_wolfstorm_anim_purple.ytyp'

dependency '/assetpacks'
